import path from "node:path";
import type { ScanContext } from "../core/context.js";
import { writeTextFile } from "../core/filesystem.js";
import { joinUrl } from "../utils/path.js";
import type { FixResult } from "./ai-assets.js";

export async function generateSeoAssets(
  context: ScanContext,
  options?: { force?: boolean },
): Promise<FixResult[]> {
  const results: FixResult[] = [];
  const productionUrl = context.config.productionUrl ?? "https://example.com";
  const projectName = context.config.projectName ?? context.inspection.projectName;
  const routes = [
    ...new Set([...context.inspection.routes, ...(context.config.criticalRoutes ?? ["/"])]),
  ].slice(0, 30);

  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (route) => `  <url>
    <loc>${joinUrl(productionUrl, route)}</loc>
    <changefreq>weekly</changefreq>
    <priority>${route === "/" ? "1.0" : "0.8"}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;

  const sitemapStatus = await writeTextFile(
    path.join(context.rootDir, "public/sitemap.xml"),
    sitemapXml,
    { force: options?.force },
  );
  results.push({ file: "public/sitemap.xml", status: sitemapStatus });

  const seoSuggestions = `# SEO Suggestions for ${projectName}

Generated by cf-ready. Review and apply manually to your source files.

## Default metadata

\`\`\`html
<title>${context.config.seo?.defaultTitle ?? projectName}</title>
<meta name="description" content="${context.config.seo?.defaultDescription ?? "Update this description"}" />
<link rel="canonical" href="${productionUrl}" />

<!-- Open Graph -->
<meta property="og:title" content="${context.config.seo?.defaultTitle ?? projectName}" />
<meta property="og:description" content="${context.config.seo?.defaultDescription ?? "Update this description"}" />
<meta property="og:image" content="${joinUrl(productionUrl, context.config.seo?.defaultImage ?? "/og.png")}" />
<meta property="og:url" content="${productionUrl}" />

<!-- Twitter/X -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${context.config.seo?.defaultTitle ?? projectName}" />
<meta name="twitter:description" content="${context.config.seo?.defaultDescription ?? "Update this description"}" />
\`\`\`

## JSON-LD Organization schema

\`\`\`html
<script type="application/ld+json">
${JSON.stringify(
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: context.config.seo?.organizationName ?? projectName,
    url: productionUrl,
  },
  null,
  2,
)}
</script>
\`\`\`

## Next.js metadata helper (App Router)

\`\`\`typescript
export const metadata = {
  title: "${context.config.seo?.defaultTitle ?? projectName}",
  description: "${context.config.seo?.defaultDescription ?? "Update this description"}",
  openGraph: {
    title: "${context.config.seo?.defaultTitle ?? projectName}",
    description: "${context.config.seo?.defaultDescription ?? "Update this description"}",
    images: ["${context.config.seo?.defaultImage ?? "/og.png"}"],
    url: "${productionUrl}",
  },
};
\`\`\`

## Image alt text

Review all <img> tags and add descriptive alt attributes.
Run \`cf-ready seo-ready\` to re-check after updates.
`;

  const suggestionsStatus = await writeTextFile(
    path.join(context.rootDir, "cf-ready-seo-suggestions.md"),
    seoSuggestions,
    { force: options?.force },
  );
  results.push({ file: "cf-ready-seo-suggestions.md", status: suggestionsStatus });

  return results;
}
